Initialization time: 2025-05-26 23:46:08
wandb: Currently logged in as: maria-i-paiva (maria-i-paiva-inesc-tec) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250526_234618-2dfpxfeq
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run resnet50_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/2dfpxfeq
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: No negative samples in targets, false positive value should be meaningless. Returning zero tensor in false positive score
  warnings.warn(*args, **kwargs)
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: No positive samples in targets, true positive value should be meaningless. Returning zero tensor in true positive score
  warnings.warn(*args, **kwargs)
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy █▁██████████████████████████████████████
wandb:             test_auroc ▆▇▄▆▅▁▄▆▄▇▇▇█▇▇▇▅▅▆█▇▄█▃▆▆▇▅▆▇▃█▃▃▄▃▂▅▄▃
wandb: test_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         test_precision ▆█▁█████████████████████████████████████
wandb:            test_recall ▆█▁█████████████████████████████████████
wandb:            train_auroc ▅▇▅▆▆▅▄█▆▁▃▃▅▄▅▅▆▄▃▅▅▃▅▆▃▅▅▄▂▂▄▁▄▄▅▅▇▃▅▃
wandb:             train_loss ▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val_accuracy ██▁█████████████████████████████████████
wandb:              val_auroc █▃▂▁▂▂▄▆▁▆▂▂▂▅▂▆▃▄▂▂▄▃▂▂▄▄▆▃▇▃▆▇▆▆▇▅▆▂▆▆
wandb:  val_balanced_accuracy █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:               val_loss █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:          val_precision ██▁█████████████████████████████████████
wandb:             val_recall ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.75
wandb:             test_auroc 0.43021
wandb: test_balanced_accuracy 0.5
wandb:         test_precision 0.75
wandb:            test_recall 0.75
wandb:            train_auroc 0.42991
wandb:             train_loss 0.64844
wandb:           val_accuracy 0.75
wandb:              val_auroc 0.65755
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 0.66649
wandb:          val_precision 0.75
wandb:             val_recall 0.75
wandb: 
wandb: 🚀 View run resnet50_3d_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/2dfpxfeq
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250526_234618-2dfpxfeq/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_001429-4dz58cdr
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run resnet50_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/4dz58cdr
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy ████▁███████████████████████████████████
wandb:             test_auroc █▅▆▇▆▆▇▆█▂▇▅▅▆▃▅▅▄▅▅▄▅▅▆▆▅▄▆▅▁▄▄▆▅▄▇▄▆▄▆
wandb: test_balanced_accuracy █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         test_precision ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            test_recall ▁█▁█████████████████████████████████████
wandb:            train_auroc █▇▃▇▅▃▅▅▄▄▄▅▂▅▆▃▄▄▄▅▇▄▂▃▁▃▃▂▃▆▄▆▅▆▆▄▂▃▄▄
wandb:             train_loss ██▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val_accuracy ▁█▁█████████████████████████████████████
wandb:              val_auroc ▇▅▄▅▇▃▃▃▄▅▆▆▅▄▅▆█▅▅▇█▃▄▄▃▆▃▁█▇█▄▃▃▅▅▆▃▆▅
wandb:  val_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:               val_loss ▃█▃▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:          val_precision ▁██▁████████████████████████████████████
wandb:             val_recall ▁██▁████████████████████████████████████
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.75
wandb:             test_auroc 0.50958
wandb: test_balanced_accuracy 0.5
wandb:         test_precision 0.75
wandb:            test_recall 0.75
wandb:            train_auroc 0.36581
wandb:             train_loss 0.6817
wandb:           val_accuracy 0.75
wandb:              val_auroc 0.47917
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 0.68578
wandb:          val_precision 0.75
wandb:             val_recall 0.75
wandb: 
wandb: 🚀 View run resnet50_3d_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/4dz58cdr
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_001429-4dz58cdr/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_010759-v6mjto80
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run resnet50_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/v6mjto80
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy ██▁█████████████████████████████████████
wandb:             test_auroc ▄▃▂▃▁▁▁▁▅▅▆▆▄▅▅█▆▄▅▇▃▆▆▆▆▇▇▇▅▆▇▆▄▆▃▃▃▄▃▄
wandb: test_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         test_precision ██▁█▁▁██████████████████████████████████
wandb:            test_recall ██▁█████████████████████████████████████
wandb:            train_auroc ▆██▆▅▆▆▄▅▄▄▅▄▁▃▄▃▂▃▅▄▄▂▃▄▄▂▃▆▃▁▅▂▄▃▂▄▃▁▃
wandb:             train_loss █▅▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val_accuracy ████▁▁██████████████████████████████████
wandb:              val_auroc █▆▁▇▆▆▃▂▄▃▇▆▅▇▅▅▅▇▆▅▄█▅▅▆▆▄▂▄▅▄▅▄▄▄▃▆▁▆▇
wandb:  val_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:               val_loss █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:          val_precision ██▁███▁█████████████████████████████████
wandb:             val_recall ██▁███▁█████████████████████████████████
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.75
wandb:             test_auroc 0.5425
wandb: test_balanced_accuracy 0.5
wandb:         test_precision 0.75
wandb:            test_recall 0.75
wandb:            train_auroc 0.43134
wandb:             train_loss 0.69195
wandb:           val_accuracy 0.75
wandb:              val_auroc 0.71745
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 0.69157
wandb:          val_precision 0.75
wandb:             val_recall 0.75
wandb: 
wandb: 🚀 View run resnet50_3d_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/v6mjto80
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_010759-v6mjto80/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_014135-1qrc0rf4
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run resnet50_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/1qrc0rf4
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy ▁█▁██▁███▁▁██▁████▁█████████████████████
wandb:             test_auroc ▅▅▃▁▃▂▄█▄▅▅▅▃▅▅▅▆▅▆▆▅▆▆▅▅▅▅▅▄▆▆▆▆▄▄▄▄▅▅▅
wandb: test_balanced_accuracy █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         test_precision ▁█▁██▁▁███▁██▁▁█████▁███████████████████
wandb:            test_recall ▁█▁█▁▁██▁▁█▁█▁███████▁██████████████████
wandb:            train_auroc ▄▃▄▄▄█▃▄▅▆▅▅▆▂▃▂▂▂▃▃▂▂▂▂▂▄▂▂▃▂▁▁▃▁▁▄▃▂▂▄
wandb:             train_loss ▄█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val_accuracy ▁█▁███▁▁██▁██▁██████▁███████████████████
wandb:              val_auroc ▅▃▄▄█▇▅▆▇▂▂▅▇▂▇▇▂▁▂▆▃▂▁▁▂▁▁▂▂▂▄▅▄▃▄▄▄▄▂▃
wandb:  val_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:               val_loss ███▂▁▁▄▂▁▂▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:          val_precision ▁█▁███▁▁█▁▁█▁▁███▁▁█████████████████████
wandb:             val_recall ▁▁███▁▁██▁▁▁▁████▁█▁████████████████████
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.75
wandb:             test_auroc 0.5025
wandb: test_balanced_accuracy 0.5
wandb:         test_precision 0.75
wandb:            test_recall 0.75
wandb:            train_auroc 0.47827
wandb:             train_loss 0.69295
wandb:           val_accuracy 0.75
wandb:              val_auroc 0.32682
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 0.69341
wandb:          val_precision 0.75
wandb:             val_recall 0.75
wandb: 
wandb: 🚀 View run resnet50_3d_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/1qrc0rf4
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_014135-1qrc0rf4/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_022419-a8el8f1s
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run resnet50_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/a8el8f1s
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
Error executing job with overrides: []
Traceback (most recent call last):
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 54, in run_hyperparameter_grid_based_execution_pipeline
    run_experiment_pipeline(config)
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 165, in run_experiment_pipeline
    model_pipeline.train_model()
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/model_pipeline.py", line 68, in train_model
    self.pytorch_lightning_trainer.fit(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 219, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 188, in run
    self._optimizer_step(kwargs.get("batch_idx", 0), closure)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 266, in _optimizer_step
    call._call_lightning_module_hook(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 146, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/core/module.py", line 1276, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/core/optimizer.py", line 161, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/strategies/strategy.py", line 231, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 116, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/optim/adam.py", line 121, in step
    loss = closure()
           ^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 103, in _wrap_closure
    closure_result = closure()
                     ^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 142, in __call__
    self._result = self.closure(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 128, in closure
    step_output = self._step_fn()
                  ^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 315, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/strategies/strategy.py", line 380, in training_step
    return self.model.training_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/resnet503d/pytorch_lightning_resnet50_3d_model.py", line 95, in training_step
    model_output = self.model(data['image'].to(self.device))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/resnet503d/resnet503d_model.py", line 20, in forward
    return self.model(model_input)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/monai/networks/nets/resnet.py", line 353, in forward
    x = self.layer1(x)
        ^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/monai/networks/nets/resnet.py", line 172, in forward
    out = self.bn2(out)
          ^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.53 GiB (GPU 0; 79.25 GiB total capacity; 77.51 GiB already allocated; 844.94 MiB free; 77.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[1;34mwandb[0m: 
[1;34mwandb[0m: 🚀 View run [33mresnet50_3d_107_160_fold1[0m at: [34mhttps://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/a8el8f1s[0m
[1;34mwandb[0m: Find logs at: [1;35m../../experiment_results/experiment_107/version_160/wandb/run-20250527_022419-a8el8f1s/logs[0m
srun: error: 02.ctm-deep-07: task 0: Exited with exit code 1
wandb: Currently logged in as: maria-i-paiva (maria-i-paiva-inesc-tec) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_022505-2vndjta2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vgg16_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/2vndjta2
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: No negative samples in targets, false positive value should be meaningless. Returning zero tensor in false positive score
  warnings.warn(*args, **kwargs)
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: No positive samples in targets, true positive value should be meaningless. Returning zero tensor in true positive score
  warnings.warn(*args, **kwargs)
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/sklearn/metrics/_classification.py:2524: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:             test_auroc ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: test_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         test_precision ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            test_recall ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            train_auroc ▆▃▆▇▆▅▅▄█▅▃▃▁▅▄▂▅▆▃▂▃▅▃▄▅▃▅▄▅▄▁▃▃▁▄▄▃▂▄▂
wandb:             train_loss █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:              val_auroc ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:  val_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:               val_loss ▁▄▅█▁▁▁█▁▁▁▂▁▂▁▁▁▁▂▂▁▁▁▁▂▁▂▂▂▂▁▁▂▂▁▁▁▁▁▁
wandb:          val_precision ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:             val_recall ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.75
wandb:             test_auroc 0.5
wandb: test_balanced_accuracy 0.5
wandb:         test_precision 0.75
wandb:            test_recall 0.75
wandb:            train_auroc 0.42876
wandb:             train_loss 0.64583
wandb:           val_accuracy 0.75
wandb:              val_auroc 0.5
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 0.66341
wandb:          val_precision 0.75
wandb:             val_recall 0.75
wandb: 
wandb: 🚀 View run vgg16_3d_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/2vndjta2
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_022505-2vndjta2/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_024713-l7i3jzs2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vgg16_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/l7i3jzs2
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
wandb: uploading wandb-summary.json; uploading config.yaml
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:             test_auroc ▁▆█▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
wandb: test_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         test_precision ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            test_recall ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            train_auroc █▃███▅▄▆▄▄▃▂▅▄▄▃▅▃▄▁▂▅▄▁▅▄▄▂▁▂▂▃▄▂▃▂▆▂▅▆
wandb:             train_loss █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:              val_auroc ▆▁▆█████████████████████████████████████
wandb:  val_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:               val_loss ▂▂▄▁█▁▂▂▁▁▂▁▁▁▁▁▁▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁
wandb:          val_precision ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:             val_recall ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.75
wandb:             test_auroc 0.5
wandb: test_balanced_accuracy 0.5
wandb:         test_precision 0.75
wandb:            test_recall 0.75
wandb:            train_auroc 0.48148
wandb:             train_loss 0.68486
wandb:           val_accuracy 0.75
wandb:              val_auroc 0.5
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 0.68534
wandb:          val_precision 0.75
wandb:             val_recall 0.75
wandb: 
wandb: 🚀 View run vgg16_3d_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/l7i3jzs2
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_024713-l7i3jzs2/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_031234-6hzf4019
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vgg16_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/6hzf4019
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:             test_auroc █▂▂▂▂▂▁▁▂▂▂▂▂▂▂▂▂▁▂▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
wandb: test_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         test_precision ▁███████████████████████████████████████
wandb:            test_recall ▁███████████████████████████████████████
wandb:            train_auroc ▄▄▇▅█▅▆▄▄▆▄▆▃▃▁▆▆▁▄▄▁▅▄▄▂▄▆▅▅▂▅▇▆▃▅▆▂▆▆▅
wandb:             train_loss █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val_accuracy ▁███████████████████████████████████████
wandb:              val_auroc ▆▆▆▆▆▆▆▆▆▆▆▁▆▇▆▆▆▆▆█▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆
wandb:  val_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:               val_loss █▂▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:          val_precision ▁███████████████████████████████████████
wandb:             val_recall ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.75
wandb:             test_auroc 0.5
wandb: test_balanced_accuracy 0.5
wandb:         test_precision 0.75
wandb:            test_recall 0.75
wandb:            train_auroc 0.44599
wandb:             train_loss 0.68983
wandb:           val_accuracy 0.75
wandb:              val_auroc 0.5
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 0.69179
wandb:          val_precision 0.75
wandb:             val_recall 0.75
wandb: 
wandb: 🚀 View run vgg16_3d_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/6hzf4019
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_031234-6hzf4019/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_041244-41rro2n2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vgg16_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/41rro2n2
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy █▁█▁████████████████████████████████████
wandb:             test_auroc ▅▃▁▂▄▄▄▁▇▃▂▅▄▄▄▄▄▄▄▄▄▃▄█▃▃▄▃▄▃▂▄▂▄▃▄▅▄▄▄
wandb: test_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         test_precision ▁█▁█████████████████████████████████████
wandb:            test_recall █▁█▁████████████████████████████████████
wandb:            train_auroc ▆▃▂▄█▄▃▃▂▅▂▃▃▂▄▄▁▃▂▄▃▅▃▃▁▃▂▃▃▃▂▃▂▄▂▂▂▂▂▂
wandb:             train_loss █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val_accuracy █▁██████████████████████████████████████
wandb:              val_auroc ▁█▃▅▅▅▅▁▄▄▄▅▃▇▅▅▅▅▅▅▅▅▅▃▅▅▅▅▅▅▅▅▄▆▅█▅▆▅▆
wandb:  val_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:               val_loss ▂▁█▃▅▂▂▁▃▃▂▂▄▁▂▂▃▂▂▂▆▃▁▂▃▂▂▂▃▃▂▂▂▃▃▃▃▂▂▂
wandb:          val_precision █▁██████████████████████████████████████
wandb:             val_recall █▁█▁████████████████████████████████████
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.75
wandb:             test_auroc 0.50292
wandb: test_balanced_accuracy 0.5
wandb:         test_precision 0.75
wandb:            test_recall 0.75
wandb:            train_auroc 0.41581
wandb:             train_loss 0.69305
wandb:           val_accuracy 0.75
wandb:              val_auroc 0.61458
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 0.69357
wandb:          val_precision 0.75
wandb:             val_recall 0.75
wandb: 
wandb: 🚀 View run vgg16_3d_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/41rro2n2
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_041244-41rro2n2/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_044628-09s80bnb
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vgg16_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/09s80bnb
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy █▁█▁█▁▁█▁█▁█▁██████████▁████████▁█████▁█
wandb:             test_auroc ▆█▂▁▄▄▃▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
wandb: test_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         test_precision █▁█▁█▁▁█▁█▁▁████▁███████▁█████████▁███▁█
wandb:            test_recall █▁█▁█▁▁█▁█▁▁████▁█████▁██▁██████████████
wandb:            train_auroc ▅▃▃█▅▄▂▅▅▂▃▃▄▃▂▁▂▃▂▃▄▃▂▂▂▂▂▂▄▂▄▂▂▃▂▁▁▃▂▂
wandb:             train_loss █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val_accuracy █▁█▁█▁▁█▁█▁▁██████████▁█████████████████
wandb:              val_auroc ▇▁▄█▄▆▄▆▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅
wandb:  val_balanced_accuracy ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:               val_loss █▃▂▃▅▁▁▁▁▃▂▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂
wandb:          val_precision █▁█▁█▁▁█▁█▁███▁█▁██████▁█▁████████▁█████
wandb:             val_recall ██▁██▁█▁██▁██▁█▁██████▁██▁██████████████
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.75
wandb:             test_auroc 0.5
wandb: test_balanced_accuracy 0.5
wandb:         test_precision 0.75
wandb:            test_recall 0.75
wandb:            train_auroc 0.42181
wandb:             train_loss 0.69611
wandb:           val_accuracy 0.75
wandb:              val_auroc 0.5
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 0.69414
wandb:          val_precision 0.75
wandb:             val_recall 0.75
wandb: 
wandb: 🚀 View run vgg16_3d_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/09s80bnb
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_044628-09s80bnb/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250527_053333-k5kgirj6
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vgg16_3d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/k5kgirj6
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 216, 1: 72
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 60, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
Error executing job with overrides: []
Traceback (most recent call last):
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 54, in run_hyperparameter_grid_based_execution_pipeline
    run_experiment_pipeline(config)
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 165, in run_experiment_pipeline
    model_pipeline.train_model()
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/model_pipeline.py", line 68, in train_model
    self.pytorch_lightning_trainer.fit(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 219, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 188, in run
    self._optimizer_step(kwargs.get("batch_idx", 0), closure)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 266, in _optimizer_step
    call._call_lightning_module_hook(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 146, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/core/module.py", line 1276, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/core/optimizer.py", line 161, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/strategies/strategy.py", line 231, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 116, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/optim/adam.py", line 121, in step
    loss = closure()
           ^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 103, in _wrap_closure
    closure_result = closure()
                     ^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 142, in __call__
    self._result = self.closure(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 128, in closure
    step_output = self._step_fn()
                  ^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 315, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/strategies/strategy.py", line 380, in training_step
    return self.model.training_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/vgg163d/pytorch_lightning_vgg163d_model.py", line 95, in training_step
    model_output = self.model(data['image'].to(self.device))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/vgg163d/vgg16_model.py", line 49, in forward
    x = self.features(x)           # (B, 512, D/32, H/32, W/32)
        ^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 613, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 608, in _conv_forward
    return F.conv3d(
           ^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.53 GiB (GPU 0; 79.25 GiB total capacity; 76.05 GiB already allocated; 988.94 MiB free; 77.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[1;34mwandb[0m: 
[1;34mwandb[0m: 🚀 View run [33mvgg16_3d_107_160_fold1[0m at: [34mhttps://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_3d_norm_resize/runs/k5kgirj6[0m
[1;34mwandb[0m: Find logs at: [1;35m../../experiment_results/experiment_107/version_160/wandb/run-20250527_053333-k5kgirj6/logs[0m
srun: error: 02.ctm-deep-07: task 0: Exited with exit code 1
Finish time: 2025-05-27 05:34:21
